name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
               SECRET_KEY: 'notsecret'
               DJANGO_ENV: 'development'
               ALLOWED_HOSTS: '*'


    steps:
    - name: Clear Actions Cache
      run: |
        rm -rf ${{ runner.workspace }}/.actions
      if: always()

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r projet/requirements.txt

    - name: Run tests
      run: pytest projet
