name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clear Actions Cache
      run: |
        rm -rf ${{ runner.workspace }}/.actions
      if: always()

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r projet/requirements.txt

    - name: Run tests
      run: pytest
